#!/bin/bash
#In most of the linux servers all the package installation are done by admin so befor erunning the script, we need to check if the user is super user or normal user 
#If we need to check who is running the script, normal user or super user, do as below
#If the user is not super user then the script throws error otherwise it proceeds further
USERID=$(id -u)
if [ $USERID -ne 0 ]
then 
   echo "Please run the script using root privilages"
   exit 1
else
   echo "You are super user"
fi
#If the exit status of the command is 0 then the script proceeds otherwise it exits
dnf install mysql-server -y
if [ $? -eq 0 ]
then
  echo "Installation of mysql...SUCCESS"
else
  echo "Installation of mysql....FAILURE"
  exit 1
fi

systemctl enable mysqld
if [ $? -eq 0 ]
then
    echo "Enabling of mysql is....SUCCESS"
else
    echo "Enabling of mysql is....FAILURE"
    exit 1
fi

systemctl start mysqld
if [ $? -eq 0 ]
then
    echo "starting of mysql is....SUCCESS"
else
    echo "starting of mysql is....FAILURE"
    exit 1
fi

mysql_secure_installation --set-root-pass ExpenseApp@1
if [$? -eq 0 ]
then
    echo "mysql root password setup....SUCCESS"
else
    echo "mysql root password setup.....FAILURE"
    exit 1
fi
